### ISSUE TITLE
$filter using expanded record fields throwing HTTP 500

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#227]
`.../Orders?$top=20&$expand=REL_OrderItems&$filter=(contains(tolower(REL_OrderItems/OrderNumber),'abc')) or (contains(tolower(REL_OrderItems/ItemNumber),'abc'))`

This is throwing an http 500 error. The following gives an HTTP 400 and says that the field ItemNumber/OrderNumber does not exist on Customers:

`.../Orders?$top=20&$expand=REL_OrderItems&$filter=(contains(tolower(OrderNumber),'abc')) or (contains(tolower(ItemNumber),'abc'))`

So, I wonder if the '/' is what is throwing the 500.

**Comment by hippiehunter** [comment]
that looks an awful lot like you might be trying to lower case a number. What do you expect that to do?

**Comment by nkim-radley** [comment]
That was a product of me mistakenly replacing the values actually being passed. They are indeed alpha strings, so I'll edit my original post for clarity.

**Comment by hippiehunter** [comment]
The Syntax you're using there to filter something nested is only valid for scalar items. this should be the correct syntax for filtering a property inside a related collection 
``` 
Customers?$expand=REL_CustomerOrders($filter=contains(CustomerReference,'c'))
```

This appears to have trouble with contains and tolower though. I'm working on fixing this query.

**Comment by nkim-radley** [comment]
I'm not sure I understand what you mean by "scalar." Does that refer to the relationship type between our schemas?

I've been looking around and found [an example](https://services.odata.org/V3/Northwind/Northwind.svc/Orders?$expand=Customer&$filter=Customer/CompanyName%20eq%20%27Vins%20et%20alcools%20Chevalier%27) from the odata site that looked similar to what DevExtreme is generating. Is this comparable?

**Comment by hippiehunter** [comment]
In the service.odata.org url you've linked, Customer is a single entity, not a collection. OrderItems in your original url, is a collection. The syntax for filtering collections is the url I posted above.

**Comment by hippiehunter** [comment]
this should be fixed if you grab the latest cli tool and do an upgrade

**Comment by nkim-radley** [comment]
I updated our HarmonyCore solution and Codegen, but I'm still running into HTTP 500s for the following request:

`...SchemaA?$top=20&$expand=REL_SchemaB&$filter=(contains(tolower(REL_SchemaB/Code),'abc')) or (contains(tolower(REL_SchemaB/Name),'abc'))`

Response in IIS log:
<pre>Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "18086456105130525070", Request ID "8000018f-0000-fb00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan.ExecuteSelectCollectionPlan[T](Func`2 tracker, IReadOnlyDictionary`2 parameters, IDataObjectProvider dataObjectProvider, Object context)
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan.ExecuteCollectionPlan[T](Func`2 tracker, IReadOnlyDictionary`2 parameters, IDataObjectProvider dataObjectProvider, Object context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.Table(QueryContext queryContext, IEntityType entityType, PreparedQueryPlan queryPlan, Boolean isTracking)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](IAsyncEnumerable`1 value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, IAsyncEnumerable`1 asyncEnumerable)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Harmony.AspNetCore.Context.IMultiTenantMiddleware.$lc994918593_InvokeMiddleware.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()</pre>

**Comment by hippiehunter** [comment]
It looks like the 'or' isnt playing nicely, shouldn't be too hard to fix. 

To make sure we're on the same page. Do you know if this is supposed to result in 
`SchemaA's where there is a SchemaB that matches the criteria` or if it results in `SchemaA's with SchemaB's where the criteria is met`

Basically does your design assume this is an inner join or a left join?

**Comment by nkim-radley** [comment]
I want to say an inner join. For context, this is a query that's being generated by DevExtreme for a search bar for a grid. Some fields in SchemaB (i.e., Rel_SchemaB/FieldName) are columns of the grid.

**Comment by hippiehunter** [comment]
Latest tool + packages should solve this usecase

**Comment by nkim-radley** [comment]
The latest update seems to have fixed my original issue. However, it seems the addition of a `...&$top=0&$count=true` is returning an empty HTTP 200 response. To note, running the queries separately (i.e., $filter and $top/$count) is returning the correct data.

**Comment by hippiehunter** [comment]
I'll take a look at it. Of note, doing a top=0 with a count is still going to read all of the data in order to produce a result. So if this is part of a pagination strategy, you would be better served by just returning the data.
