### ISSUE TITLE
Filter by Date range with format YYYYMMDD throwing HTTP 500

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#231]
In our RPS we have fields of type "Date" and class "YYYYMMDD" with the Long Description "HARMONY_AS_STRING." And I can see that the dates returned from Odata are in the format "YYYY-MM-DD." However, after trying to $filter using a date range, we get an HTTP 500.

Example query 1: `$filter=(DateField ge '20210127') and (DateField le '20210130')`

Example query 2: `$filter=(DateField ge '2021-01-27') and (DateField le '2021-01-30')`

The IIS log:
<pre>Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "18014398511092597720", Request ID "800003d9-0000-fa00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan.ExecuteSelectCollectionPlan[T](Func`2 tracker, IReadOnlyDictionary`2 parameters, IDataObjectProvider dataObjectProvider, Object context)
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan.ExecuteCollectionPlan[T](Func`2 tracker, IReadOnlyDictionary`2 parameters, IDataObjectProvider dataObjectProvider, Object context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.Table(QueryContext queryContext, IEntityType entityType, PreparedQueryPlan queryPlan, Boolean isTracking)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](IAsyncEnumerable`1 value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, IAsyncEnumerable`1 asyncEnumerable)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Harmony.AspNetCore.Context.IMultiTenantMiddleware.$lc994918593_InvokeMiddleware.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
</pre>

**Comment by hippiehunter** [comment]
I just tried this with "/odata/v1/Customers?$filter=(Phone ge '(555) 900-0000') and (Phone le '(555) 920-0000')" and it seems to be happy generally with formatted string -> number mappings. Can I see the code for property get/set for 'Datetime' Also there should be a reference to the 'Datetime' field in your StructureNameMetadata.dbl file, something like  https://github.com/Synergex/HarmonyCore/blob/de2b3df98afc2849d271ab29eb54730ec56748d2/Services.Models/CustomerMetaData.dbl#L52

**Comment by nkim-radley** [comment]
<pre>
        ;;; <summary>
        ;;; Insertion date
        ;;; </summary>
        public property Dj1Date, String
            method get
            proc
                mreturn %string(mSynergyData.dj1_date,"XXXX-XX-XX")
            endmethod
            method set
            proc
                mSynergyData.dj1_date = SynergyDecimalConverter.ConvertBack(value,"XXXX-XX-XX")
            endmethod
        endproperty</pre>

**Comment by hippiehunter** [comment]
This should be resolved in the latest version
