### ISSUE TITLE
orderby not working on expanded fields

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#244]
Getting HTTP 500 for orderby on expanded fields:

Example URL: 

<pre>
Example URL: ../odata/v1/FileA?$orderby=REL_FileB/BFieldName&$top=20&$expand=REL_FileB&$count=true
</pre>

**Comment by hippiehunter** [comment]
I'm not actually getting an HTTP 500 from this query are you running the current version? There is a bit of an issue in that when i run this its not actually ordering the data as expected. I can fix the ordering problem pretty easily but its emulating orderby so it will load the entire query result, order it and then return the top 20. If you want the orderby to run using an isam key, you will need to do the join the other direction ex. ./odata/v1/FileB?$orderby=BFieldName&$top=20&$expand=REL_FileA&$count=true

**Comment by nkim-radley** [comment]
Is it possible that you're not running into the same issue because we are not at the latest version of Harmony Core?

**Comment by hippiehunter** [comment]
that's very possible.

**Comment by nkim-radley** [comment]
I can create another issue for this, but I am getting an error when trying to run regen:

`ERROR: Invalid expression <IF IF> at offset 14733!`

**Comment by theplasmastorm** [comment]
Hello.

Could you double check that you're on the latest Codegen version? If not, install it and try again
https://github.com/Synergex/CodeGen/releases/tag/v5.6.9

If it still doesn't work, what part of the regen is failing for you, exactly?

**Comment by nkim-radley** [comment]
Thank you for the reminder. That seemed to get me past the error. I am now running into a new error:'

`ERROR: Template INTERFACEPOSTMANTESTS requires a user-defined token API_TITLE which is not defined.`

Is this implying that I need to define `API_TITLE` in my app.settings.json?

**Comment by theplasmastorm** [comment]
We may have missed something in the regen.bat file.

If you open it up and scroll down to line 588, where `InterfacePostmanTests` are mentioned, go ahead and edit it so that the regen will pass in the `API_TITLE` user token.

Your change will look similar to this:
```
  codegen -smc %SMC_XML_FILE% ^
          -interface %1 ^
          -t InterfacePostmanTests ^
          -i %SolutionDir%Templates\TraditionalBridge ^
          -o %SolutionDir% ^
          -ut API_TITLE=[your_api_title_here]
            %STDOPTS%
```

**Comment by SteveIves** [comment]
API_TITLE generally comes from UserDefinedTokens.xml. Check there, and make sure the file is being named on the CodeGen command.

**Comment by nkim-radley** [comment]
I'm a bit confused what the expected command is. I am not seeing the UserDefinedTokens.tkn file in the command. This is what we have for generating the Postman tests in regen.bat:

<pre>
  rem Generate the Postman tests for the Interface

  codegen -smc %SMC_XML_FILE% ^
          -interface %SMC_INTERFACE% ^
          -t InterfacePostmanTests ^
          -i %SolutionDir%Templates\TraditionalBridge ^
          -o %SolutionDir% ^
          %STDOPTS%
  if ERRORLEVEL 1 goto error
</pre>

**Comment by theplasmastorm** [comment]
Steve's comment is a correction to mine. He is saying that you should make sure that `API_TITLE` is defined in your `UserDefinedTokens.tkn` file. It should exist in your HarmonyCore root folder.

It should be a file that looks similar to this: https://github.com/Synergex/HarmonyCore/blob/master/UserDefinedTokens.tkn

**Comment by nkim-radley** [comment]
I updated the command to include the API_TITLE value and this seemed to fix the regen issue. Is there no way to reuse the value as defined by `UserDefinedTokens.tkn`? Or is that what Steve was implying?

Regardless, I am now running into build issues:

![image](https://user-images.githubusercontent.com/52933970/112040992-3cc7bc00-8b1c-11eb-8bb1-216038a581e9.png)

**Comment by theplasmastorm** [comment]
Correct. Regen.bat will read tokens from `UserDefinedTokens.tkn`, including `API_TITLE`

**Comment by nkim-radley** [comment]
Previous to making changes to my regen.bat, the `UserDefinedtokens.tkn` file always had the `API_TITLE` defined. Am I missing something? My command to generate the Postman interface tests looks like this now:

<pre>
codegen -smc %SMC_XML_FILE% ^
          -interface %SMC_INTERFACE% ^
          -t InterfacePostmanTests ^
          -i %SolutionDir%Templates\TraditionalBridge ^
          -o %SolutionDir% ^
          -ut API_TITLE="Radley OData Services" ^
            %STDOPTS%
  if ERRORLEVEL 1 goto error
</pre>

But it sounds like there a way to avoid explicitly defining the title here.

**Comment by nkim-radley** [comment]
And in regards to my build issues, I'm running on 10.3.3g and the latest version of Harmony Core and Code Gen.

**Comment by SteveIves** [comment]
Notice the %STDOPTS% in the CodeGen command. It includes:

-u %SolutionDir%UserDefinedTokens.tkn

Which causes CodeGeb to read User defined tokens from the .tkn file.

**Comment by nkim-radley** [comment]
This is what I have:

<pre>
set NOREPLACEOPTS=-e -lf -u %SolutionDir%UserDefinedTokens.tkn [...]
set STDOPTS=%NOREPLACEOPTS% -r
</pre>

**Comment by theplasmastorm** [comment]
I have made changes that will fix your issue here 88009d7cfac1f931244b9b7a5023d3f06825cd43, if you wish to merge my changes into your code.
These changes are 10.3.3 specific

**Comment by SteveIves** [comment]
exactly

**Comment by nkim-radley** [comment]
@SteveIves I think we might be on different pages. I've had the `STDOPTS` set as I posted this entire time. My issue is that, as per @theplasmastorm noted in his example, unless I explicitly set the `API_TITLE` in the codegen command, `regen` complains about the `API_TITLE` not being defined. 

In other words, do I need to have `-ut API_TITLE="Radley OData Services" ^` in my command in order for `regen` to not complain? According to what Steve is saying, it sounds like I don't need to, but I'm experiencing otherwise.

In regards to the build issue, I will also circle back once I am able to test the change.

**Comment by SteveIves** [comment]
You should not have to define API_TITLE on the command line, it is obtained from the UserDefinedTokens.tkn file. If that is not working then there is something wrong.

**Comment by nkim-radley** [comment]
In regards to regen, I will double check that the issue with regen persists with the hotfix and write up a separate issue.

In regards to the original issue reported, (with the hotfix) I still get HTTP 500. This is what I see in the IIS log:

<pre>
System.InvalidOperationException: The binary operator LessThan is not defined for the types 'System.String' and 'System.String'.
   at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.GetComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.LessThan(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at System.Linq.Expressions.Expression.LessThan(Expression left, Expression right)
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan.Prepare()
   at Harmony.Core.FileIO.Queryable.PreparedQueryPlan..ctor(Boolean isCollection, IEnumerable`1 whereParts, Dictionary`2 sparseParts, IEnumerable`1 onParts, List`1 orderBy, QueryBuffer queryBufferPrototype, String traceIdentifier)
   at Harmony.Core.EF.Query.Internal.HarmonyQueryExpression.PrepareQuery(MethodInfo tableMethodInfo, ParameterExpression queryContextParameter, HarmonyQueryCompilationContext compilationContext)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.VisitShapedQueryExpression(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at Harmony.Core.EF.Query.Internal.HarmonyShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
</pre>

**Comment by hippiehunter** [comment]
I don't see a greater than or less than operator in any of the queries you've supplied recently. What is the url for this request? Are there [tags](https://github.com/Synergex/HarmonyCore/wiki/Repository-Setup#defining-tags) in any of the structures involved in that query?

**Comment by nkim-radley** [comment]
The URL is as I posted in my initial report. My guess is the comparison is coming from processing the ordering (ascending or descending) of the records.

I am looking into whether or not we have tags.

**Comment by hippiehunter** [comment]
I'm looking into your stack trace but my original comment on this issue still stands. orderby on a related field isn't currently supported and you would be better served by writing your query in the other direction `./odata/v1/FileB?$orderby=BFieldName&$top=20&$expand=REL_FileA&$count=true`

**Comment by nkim-radley** [comment]
This is a query that is being generated by our frontend framework when we enable grid column sorting. If we customize the URL generated per column, this will cause overhead for the front-end to handle the query creation and I don't think this is ideal. Is the support for $orderby on an expanded field in the plans to be implemented?

And can we also anticipate a fix for the order of the results that you mentioned in your first comment?

**Comment by hippiehunter** [comment]
I can make the query work in the next few days but it wont be optimal and it will have to process all records for the query not just the top 20. Automatically recognizing and reordering the query is a much larger task that I can probably fold into some larger work we're doing over the next 6 months.

**Comment by hippiehunter** [comment]
I've done a new release with the emulated fix for this problem. You should be able to get it from the cli tool. Let me know if its fixed so I can close this issue and open one for optimizing based on related key fields.

**Comment by nkim-radley** [comment]
I can double check if this is still occurring but want to confirm what exactly was fixed in the latest Harmony Core update. After updating Harmony Core to the latest revision, the HTTP 500 errors went away, but the order of the records do not seem to reflect ascending or descending (as specified by my odata request).

**Comment by hippiehunter** [comment]
The crash was fixed and orderby emulation is present. It should perform the order by operation you're asking for but it will have to read the entire result under the hood and then apply the orderby.  

When I run this test https://github.com/Synergex/HarmonyCore/blob/416c85e45223bcacdadf1fc04da41078f776f6f1/Services.Test/UnitTests/HandCrafted.dbl#L243 I can see the returned data is in the correct order. What is different with your query.

**Comment by hippiehunter** [comment]
you're using the DevExtreme controls right? if so you can use this to work around this until we have more complete/optimized support for orderby https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/remoteOperations/ it looks like you can set it to do sorting locally instead of remote, without effecting filtering or initial load.

**Comment by nkim-radley** [comment]
Using DevExtreme's remoteOperations allows us to do client-side sorting. So, we have a work around for now.
