### ISSUE TITLE
Harmony Core Regen CLI reporting "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by tscaff** [Synergex/HarmonyCore#381]
Since I have been unable to fix this myself, I thought it was probably time to post this to the issues site.  

I recently upgraded to the CLI version 8.0.74, as shown.

dotnet tool list -g
Package Id                Version      Commands
--------------------------------------------------
harmony.core.clitool      8.0.74       harmonycore

After an update to the VC++ Redistributable package to version 14.42.34433 I started receiving the following error message when trying to perform a 'harmonycore regen' CLI command.

Application: harmonycore.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeGen.RepositoryAPI.RpsStructureCollection..ctor(Repository aRepository, RpsLoadMode LoadMode, Boolean UseAlternateFieldNames) in D:\dev\agent\_work\1\s\CodeGen\RepositoryAPI\RpsStructureCollection.dbl:line 65
   at HarmonyCoreGenerator.Model.Solution.GenerateSolution(SolutionGenerationEvents handlers, CancellationToken cancelToken, Dictionary`2 additionalGenerators) in D:\dev\agent\_work\1\s\CodeGen\HarmonyCoreCodeGen.Core\Model\Solution.dbl:line 1386
   at HarmonyCore.CliTool.Commands.RegenCommand.Run(RegenOptions opts, Dictionary`2 syncAddedFiles, Dictionary`2 syncRemovedFiles) in D:\dev\agent\_work\1\s\HarmonyCore.CliTool\Commands\RegenCommand.cs:line 70
   at HarmonyCore.CliTool.Commands.RegenCommand.Run(RegenOptions opts) in D:\dev\agent\_work\1\s\HarmonyCore.CliTool\Commands\RegenCommand.cs:line 45
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 parsedFunc6, Func`2 parsedFunc7, Func`2 parsedFunc8, Func`2 parsedFunc9, Func`2 parsedFunc10, Func`2 notParsedFunc)
   at HarmonyCore.CliTool.Program.ProcessCommandArgs(String[] args) in D:\dev\agent\_work\1\s\HarmonyCore.CliTool\Program.cs:line 412
   at HarmonyCore.CliTool.Program.Main(String[] args) in D:\dev\agent\_work\1\s\HarmonyCore.CliTool\Program.cs:line 402

I am the only one experiencing this, but I am the only one on our team, as far as I know, who has installed the latest VC++ redistributable packages as I was installing the latest version of Locust for load testing when this started occurring.  

I have been unable to repair this and continue to fail on my regen attempts.

**Comment by tscaff** [comment]
I was able to attach a debugger using the source code from GitHub and it appears that the repository object goes null at the lines indicated by the stack trace.

                mRepository.CheckIsOpen()
                
The only thing I can't synchronize with to debug is the Solutions.dbl code in HarmonyCore\CodeGen\HarmonyCoreCodeGen.Core\Model.  It does not appear to match the main branch checked in version.  Line 1386 doesn't match what is in current main code.  Is that expected?

**Comment by hippiehunter** [comment]
I think it will work if you update your cli to .76

**Comment by tscaff** [comment]
How do I get .76? I only see 8.0.74 when I search for it....

CoreRelease2025>C:\Dev\CoreDirectorDBL>dotnet tool search Harmony.Core.CliTool
Package ID                Latest Version      Authors                   Downloads      Verified
-----------------------------------------------------------------------------------------------
harmony.core.clitool      8.0.74              Harmony.Core.CliTool      16265

**Comment by hippiehunter** [comment]
https://www.nuget.org/packages/Harmony.Core.CliTool

sometimes it takes a few minutes for nuget/dotnet tool to figure out something has happened. Try again in a few minutes.

**Comment by tscaff** [comment]
Ok, I see it now.

harmony.core.clitool      8.0.76              Harmony.Core.CliTool      16265

And yes, that seems to have fixed it.  

harmonycore regen
SolutionDir '' is not set. Using the current working directory.
Scanning '***' for HarmonyCore project files
Using MSBuild from path: C:\Program Files\dotnet\sdk\8.0.404

InterfaceController : Task complete, 1 file generated.
InterfaceController : Task complete, 1 file generated.
InterfaceController : Task complete, 1 file generated.
InterfaceController : Task complete, 1 file generated.
InterfaceSuperDispatcher : Task complete, 1 file generated.
TraditionalModel,TraditionalMetadata : Task complete, 1474 files generated.

So, the exception I was seeing was not really anything to do with my V++ redistributable update, was it?

**Comment by hippiehunter** [comment]
no, it was just a bug in the cli tool
